name = "Symbols"
uuid = "66511b27-2878-41d4-8ecd-6d38007fc4c5"
authors = ["Matheus Diógenes Andrade <matheusdiogenesandrade@gmail.com> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
